# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rspec-github` gem.
# Please instead update this file by running `bin/tapioca gem rspec-github`.


# source://rspec-github//lib/rspec/github/version.rb#3
module RSpec
  class << self
    # source://rspec-core/3.13.5/lib/rspec/core.rb#70
    def clear_examples; end

    # source://rspec-core/3.13.5/lib/rspec/core.rb#85
    def configuration; end

    # source://rspec-core/3.13.5/lib/rspec/core.rb#49
    def configuration=(_arg0); end

    # source://rspec-core/3.13.5/lib/rspec/core.rb#97
    def configure; end

    # source://rspec-core/3.13.5/lib/rspec/core.rb#194
    def const_missing(name); end

    # source://rspec-core/3.13.5/lib/rspec/core/dsl.rb#42
    def context(*args, &example_group_block); end

    # source://rspec-core/3.13.5/lib/rspec/core.rb#122
    def current_example; end

    # source://rspec-core/3.13.5/lib/rspec/core.rb#128
    def current_example=(example); end

    # source://rspec-core/3.13.5/lib/rspec/core.rb#154
    def current_scope; end

    # source://rspec-core/3.13.5/lib/rspec/core.rb#134
    def current_scope=(scope); end

    # source://rspec-core/3.13.5/lib/rspec/core/dsl.rb#42
    def describe(*args, &example_group_block); end

    # source://rspec-core/3.13.5/lib/rspec/core/dsl.rb#42
    def example_group(*args, &example_group_block); end

    # source://rspec-core/3.13.5/lib/rspec/core/dsl.rb#42
    def fcontext(*args, &example_group_block); end

    # source://rspec-core/3.13.5/lib/rspec/core/dsl.rb#42
    def fdescribe(*args, &example_group_block); end

    # source://rspec-core/3.13.5/lib/rspec/core.rb#58
    def reset; end

    # source://rspec-core/3.13.5/lib/rspec/core/shared_example_group.rb#110
    def shared_context(name, *args, &block); end

    # source://rspec-core/3.13.5/lib/rspec/core/shared_example_group.rb#110
    def shared_examples(name, *args, &block); end

    # source://rspec-core/3.13.5/lib/rspec/core/shared_example_group.rb#110
    def shared_examples_for(name, *args, &block); end

    # source://rspec-core/3.13.5/lib/rspec/core.rb#160
    def world; end

    # source://rspec-core/3.13.5/lib/rspec/core.rb#49
    def world=(_arg0); end

    # source://rspec-core/3.13.5/lib/rspec/core/dsl.rb#42
    def xcontext(*args, &example_group_block); end

    # source://rspec-core/3.13.5/lib/rspec/core/dsl.rb#42
    def xdescribe(*args, &example_group_block); end
  end
end

# source://rspec-github//lib/rspec/github/version.rb#4
module RSpec::Github; end

# source://rspec-github//lib/rspec/github/formatter.rb#9
class RSpec::Github::Formatter < ::RSpec::Core::Formatters::BaseFormatter
  # source://rspec-github//lib/rspec/github/formatter.rb#12
  def example_failed(failure); end

  # source://rspec-github//lib/rspec/github/formatter.rb#18
  def example_pending(pending); end

  # source://rspec-github//lib/rspec/github/formatter.rb#24
  def seed(notification); end
end

# source://rspec-github//lib/rspec/github/notification_decorator.rb#5
class RSpec::Github::NotificationDecorator
  # @return [NotificationDecorator] a new instance of NotificationDecorator
  #
  # source://rspec-github//lib/rspec/github/notification_decorator.rb#13
  def initialize(notification); end

  # source://rspec-github//lib/rspec/github/notification_decorator.rb#21
  def annotation; end

  # source://rspec-github//lib/rspec/github/notification_decorator.rb#17
  def line; end

  # source://rspec-github//lib/rspec/github/notification_decorator.rb#26
  def path; end

  private

  # source://rspec-github//lib/rspec/github/notification_decorator.rb#33
  def example; end

  # source://rspec-github//lib/rspec/github/notification_decorator.rb#37
  def message; end

  # source://rspec-github//lib/rspec/github/notification_decorator.rb#45
  def raw_path; end

  # source://rspec-github//lib/rspec/github/notification_decorator.rb#49
  def workspace; end
end

# See https://github.community/t/set-output-truncates-multiline-strings/16852/3.
#
# source://rspec-github//lib/rspec/github/notification_decorator.rb#7
RSpec::Github::NotificationDecorator::ESCAPE_MAP = T.let(T.unsafe(nil), Hash)

# source://rspec-github//lib/rspec/github/version.rb#5
RSpec::Github::VERSION = T.let(T.unsafe(nil), String)
