# For all options see https://github.com/bbatsov/rubocop/tree/master/config

inherit_gem:
  gc_ruboconfig: rubocop.yml

require:
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - .*/**/*
    - bin/**/*
    - lib/**/templates/**/*
    - spec/nandi/fixtures/**/*
    - node_modules/**/*
    - vendor/**/*

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 20

Gemspec/RequiredRubyVersion:
  Enabled: false
