version: 2.1

references:
  bundle_install: &bundle_install
    run:
      name: Bundle
      command: |
        gem install bundler --no-document && \
        bundle config set no-cache 'true' && \
        bundle config set jobs '4' && \
        bundle config set retry '3' && \
        bundle install

  cache_bundle: &cache_bundle
    save_cache:
      key: bundle-<< parameters.ruby_version >>-{{ checksum "nandi.gemspec" }}-{{ checksum "Gemfile" }}
      paths:
        - vendor/bundle

  restore_bundle: &restore_bundle
    restore_cache:
      key: bundle-<< parameters.ruby_version >>-{{ checksum "nandi.gemspec" }}-{{ checksum "Gemfile" }}

jobs:
  rspec:
    working_directory: ~/nandi
    parameters:
      ruby_version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby_version >>
    steps:
      - add_ssh_keys
      - checkout
      - *restore_bundle
      - *bundle_install
      - *cache_bundle
      - run:
          name: Run specs
          command: bundle exec rspec
      - run:
          name: "Rubocop"
          command: bundle exec rubocop

workflows:
  version: 2
  tests:
    jobs:
      - rspec:
          matrix:
            parameters:
              ruby_version: ["2.6", "2.7", "3.0", "3.1"]
