version: 2

references:
  steps: &steps
    - checkout
    - run: gem install bundler
    - run: bundle install
    - run: bundle exec rspec spec

jobs:
  rubocop:
    docker:
      - image: 'ruby:2.6'
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rubocop

  ruby27:
    docker:
      - image: 'ruby:2.7'
    steps: *steps
  ruby26:
    docker:
      - image: 'ruby:2.6'
    steps: *steps
  ruby25:
    docker:
      - image: 'ruby:2.5'
    steps: *steps
  ruby24:
    docker:
      - image: 'ruby:2.4'
    steps: *steps

workflows:
  version: 2
  tests:
    jobs:
      - rubocop
      - ruby27
      - ruby26
      - ruby25
      - ruby24
