#!/usr/bin/env ruby

# frozen_string_literal: true

require "bundler"
Bundler.setup(:default)

require "slop"

require_relative "../lib/nandi/safe_migration_enforcer"

opts = Slop.parse do |o|
  o.string "--safe-migration-dir", "directory containing Nandi migrations"
  o.string "--ar-migration-dir", "directory containing ActiveRecord migrations"
  o.on "-h", "--help" do
    puts o
    exit
  end
end

present_opts = opts.to_hash.reject { |_, value| value.nil? }

enforcer = Nandi::SafeMigrationEnforcer.new(present_opts)

enforcer.run
