#!/bin/bash
set -e
echo "Installing dependencies for nandi..."
DIR=$(dirname $0)
pushd $(dirname $DIR)
  bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
popd
