#!/bin/bash
set -e
echo "Running tests for nandi..."
DIR=$(dirname $0)
pushd $(dirname $DIR)
  bundle exec rspec --format RspecJunitFormatter --out $CIRCLE_TEST_REPORTS/rspec/nandi.xml --format progress
popd
