name: tests

on:
  push:
    branches:
      - master
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rubocop --parallel --extra-details --display-style-guide

  tests:
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ["3.3", "3.4", "4.0"]
        rails-version: ["7.2", "8.0", "8.1"]
    runs-on: ubuntu-latest
    env:
      RAILS_VERSION: "~> ${{ matrix.rails-version }}"
    steps:
      - uses: actions/checkout@v6
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby-version }}"
          bundler-cache: false
      - name: Install dependencies with Rails ${{ matrix.rails-version }}
        run: bundle install
      - name: Run tests
        run: bundle exec rspec --profile --format progress --format RSpec::Github::Formatter
